backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
display_url: https://github.com/devinea/mvx19-cms/pulls

collections:
  - name: "fioriwebguideline"
    label: "Fiori Web"
    folder: "src/pages/designguideline"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "design-guideline-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", tagname: ''}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Fundamentals Docs Path", name: "fundamentalsFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental/components", required: false}
      - {label: "Angular Docs Path", name: "angularFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-ngx", required: false}
      - {label: "React Docs Path", name: "reactFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-react", required: false}
      - {label: "isControl", name: "iscontrol", widget: "boolean", default: true, required: false}
      - {label: "Version No.", name: "version", widget: "select", options: ["1.01", "1.02", "1.03","1.04", "1.05"]}
      - label: "Left Nav Order"
        name: "leftnavorder"
        widget: "object"
        fields:
          - {label: "Level 1", name: "l1", widget: "number", default: 4}
          - {label: "Level 2", name: "l2", widget: "number", default: 1}
          - {label: "Level 3", name: "l3", widget: "number", default: 0}
          - {label: "Level 4", name: "l4", widget: "number", default: 0}
  - name: "fioriiosguideline"
    label: "Fiori IOS"
    folder: "src/pages/guideline_ios"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "design-guideline-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", tagname: ''}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Fundamentals Docs Path", name: "fundamentalsFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental/components", required: false}
      - {label: "Angular Docs Path", name: "angularFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-ngx", required: false}
      - {label: "React Docs Path", name: "reactFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-react", required: false}
      - {label: "isControl", name: "iscontrol", widget: "boolean", default: true, required: false}
      - {label: "Version No.", name: "version", widget: "select", options: ["1.01", "1.02", "1.03","1.04", "1.05"]}
      - label: "Left Nav Order"
        name: "leftnavorder"
        widget: "object"
        fields:
          - {label: "Level 1", name: "l1", widget: "number", default: 4}
          - {label: "Level 2", name: "l2", widget: "number", default: 1}
          - {label: "Level 3", name: "l3", widget: "number", default: 0}
          - {label: "Level 4", name: "l4", widget: "number", default: 0}
  - name: "fioriandroidguideline"
    label: "Fiori Android"
    folder: "src/pages/guideline_android"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "design-guideline-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Featured Image", name: "featuredImage", widget: "image", tagname: ''}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Fundamentals Docs Path", name: "fundamentalsFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental/components", required: false}
      - {label: "Angular Docs Path", name: "angularFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-ngx", required: false}
      - {label: "React Docs Path", name: "reactFile", widget: "fileSelect", url: ".netlify/git/github/contents/static/docs/fundamental-react", required: false}
      - {label: "isControl", name: "iscontrol", widget: "boolean", default: true, required: false}
      - {label: "Version No.", name: "version", widget: "select", options: ["1.01", "1.02", "1.03","1.04", "1.05"]}
      - label: "Left Nav Order"
        name: "leftnavorder"
        widget: "object"
        fields:
          - {label: "Level 1", name: "l1", widget: "number", default: 4}
          - {label: "Level 2", name: "l2", widget: "number", default: 1}
          - {label: "Level 3", name: "l3", widget: "number", default: 0}
          - {label: "Level 4", name: "l4", widget: "number", default: 0}
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Featured Image", name: "featuredImage", widget: "image", tagname: ''}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
  - name: "learning"
    label: "Learning"
    folder: "src/pages/learning"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
    - {label: "Template Key", name: "templateKey", widget: "hidden", default: "learning-post"}
    - {label: "Title", name: "title", widget: "string"}
    - {label: "Publish Date", name: "date", widget: "datetime"}
    - {label: "Description", name: "description", widget: "text"}
    - {label: "Body", name: "body", widget: "markdown"}
    - {label: "Tags", name: "tags", widget: "list"}
